### ISSUE TITLE
import kinet2pcb # error in kicad 6.0.9 python 3.914

### ISSUE THREAD

**Issue by QGB** [devbisme/kinet2pcb#9]
```
---------------------------
wxWidgets Debug Alert
---------------------------
..\..\pcbnew\action_plugin.cpp(163): assert "PgmOrNull()" failed in ACTION_PLUGINS::register_action().
Do you want to stop the program?
You can also choose [Cancel] to suppress further warnings.
---------------------------
是(Y)   否(N)   取消   
---------------------------
````

**Comment by QGB** [comment]
![image](https://user-images.githubusercontent.com/8005654/200020967-eec03839-62c7-43e9-807e-3cdfbfddaaa0.png)

**Comment by QGB** [comment]
```
In [12]: !"C:/Program Files/KiCad/6.0/bin/python.exe"  C:\QGB\babun\cygwin\bin\qgb\tests\skidl_test.py
WARNING: KICAD_SYMBOL_DIR environment variable is missing, so the default KiCad symbol libraries won't be searched. @ [C:\test\jlc-eda\<frozen importlib._bootstrap_external>:850=>C:\test\jlc-eda\<frozen importlib._bootstrap>:228]
WARNING: Could not load KiCad schematic library "Device", falling back to backup library. @ [C:\QGB\babun\cygwin\bin\qgb\tests\skidl_test.py:9]
WARNING: Could not load KiCad schematic library "Device", falling back to backup library. @ [C:\QGB\babun\cygwin\bin\qgb\tests\skidl_test.py:10]
WARNING: Could not load KiCad schematic library "power", falling back to backup library. @ [C:\QGB\babun\cygwin\bin\qgb\tests\skidl_test.py:17]
WARNING: Could not load KiCad schematic library "power", falling back to backup library. @ [C:\QGB\babun\cygwin\bin\qgb\tests\skidl_test.py:18]

No errors or warnings found while generating netlist.

Traceback (most recent call last):
  File "C:\QGB\babun\cygwin\bin\qgb\tests\skidl_test.py", line 31, in <module>
    print(generate_pcb())
  File "C:\Users\qgb\Documents\KiCad\6.0\3rdparty\Python39\site-packages\skidl\circuit.py", line 562, in generate_pcb
    gen_func(file_)  # Generate the PCB file from the netlist.
  File "C:\Users\qgb\Documents\KiCad\6.0\3rdparty\Python39\site-packages\skidl\tools\kicad\kicad.py", line 1004, in gen_pcb
    kinet2pcb.kinet2pcb(self, file_)
  File "C:\Users\qgb\Documents\KiCad\6.0\3rdparty\Python39\site-packages\kinet2pcb\kinet2pcb.py", line 219, in kinet2pcb
    fp_lib, fp_name = part.footprint.split(":")
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by QGB** [comment]
pdb debug 
![image](https://user-images.githubusercontent.com/8005654/200022624-5a2fbc6d-4a78-41da-a87a-8042fde24a56.png)

**Comment by QGB** [comment]
`In [28]: !"C:/Program Files/KiCad/6.0/bin/python.exe" -c __import__('hierplace')`

**Comment by QGB** [comment]
```
In [36]: from hierplace.HierPlace import HierPlace

In [37]: HierPlace()
Out[37]: <hierplace.HierPlace.HierPlace at 0x1311f2b3ca0>

In [38]: _pcbnew.PYTHON_ACTION_PLUGINS_register_action(_37)
```

**Comment by devbisme** [comment]
This looks like a repeat or a very similar version of a previous issue. I'm going to close it since it will be handled in the other issue.
